version: "2"
linters:
  default: all
  disable:
    - gochecknoglobals
    - gochecknoinits
    - interfacebloat
    - nonamedreturns
    - varnamelen
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*ecc/Element).MarshalBinary
        - (*ecc/Scalar).MarshalBinary
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      default-case-required: true
    exhaustruct:
      exclude:
        - '.+/._'
    gocritic:
      enable-all: true
      disabled-checks:
        - commentedOutCode
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    interfacebloat:
      max: 11
    ireturn:
      allow:
        - error
        - generic
        - internal.Element
        - internal.Group
        - internal.Scalar
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '2'
        - '3'
        - '7'
        - '8'
        - '10'
        - '33'
      ignored-functions:
        - 'nist.setMapping'
        - 'big.NewInt'
        - 'hash2curve.HashToFieldXMD'
    nlreturn:
      block-size: 2
    prealloc:
      simple: false
      for-loops: true
  exclusions:
    rules:
      - linters:
          - exhaustruct
        text: "is missing field _"
      - path: debug/debug\.go
        linters:
          - dupl
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/ecc)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/ecc
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false